AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template to deploy Nucleus APIs

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 100
Resources:
  NucleusSupplyBusTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "Nucleus Supply Bus"
      FifoTopic: false
      TopicName: !Sub "aew-nucleus-supply-bus-${AWS::StackName}"
########### START WATER
  NucleusWaterApi:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Description: API for AEW Nucleus for Water.
      CodeUri: ./AEW.Nucleus.Water.API/src/AEW.Nucleus.Water.API/
      Handler: AEW.Nucleus.Water.API
      Runtime: dotnet6
      MemorySize: 128    
      Events:
        ProxyResource:
          Type: HttpApi
          Properties:
            PayloadFormatVersion: '2.0'
            Path: water/{proxy+}
            Method: ANY
        RootResource:
          PayloadFormatVersion: '2.0'
          Type: HttpApi
          Properties:
            Path: water/
            Method: ANY
      Environment:
        Variables:
          NUCLEUS_SUPPLY_TOPIC__REGION: !Ref 'AWS::Region'
          NUCLEUS_SUPPLY_TOPIC__ARN: 'arn:aws:sns:us-east-1:686681529839:iws-core-supply-proto-001'
          HIVE__BUCKET__NAME: !Sub 'aew-nucleus-water-${AWS::StackName}'
          HIVE__BUCKET__REGION: !Ref 'AWS::Region'
      Policies:
      - 'AWSLambdaBasicExecutionRole'
      - Statement:
        - Sid: 'NuclearWaterPersistencePolicy'
          Effect: Allow
          Action:
            - 's3:PutObject'
            - 's3:GetObject'
            - 's3:GetObjectAttributes'
            - 's3:GetObjectTagging'
            - 's3:DeleteObject'
          Resource: !Sub 'arn:aws:s3:::aew-nucleus-water-${AWS::StackName}/*'
  NucleusWaterS3:
    Type: AWS::S3::Bucket
    Description: 'S3 for AEW Nucleus for Water'
    Properties:
      BucketName: !Sub 'aew-nucleus-water-${AWS::StackName}'
########### END WATER
########### START FOOD
  NucleusFoodApi:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Description: API for AEW Nucleus for Food.
      CodeUri: ./AEW.Nucleus.Food.API/src/AEW.Nucleus.Food.API/
      Handler: AEW.Nucleus.Food.API
      Runtime: dotnet6
      MemorySize: 128    
      Events:
        ProxyResource:
          Type: HttpApi
          Properties:
            PayloadFormatVersion: '2.0'
            Path: food/{proxy+}
            Method: ANY
        RootResource:
          PayloadFormatVersion: '2.0'
          Type: HttpApi
          Properties:
            Path: food/
            Method: ANY
      Environment:
        Variables:
          NUCLEUS_SUPPLY_TOPIC__REGION: !Ref 'AWS::Region'
          NUCLEUS_SUPPLY_TOPIC__ARN: 'arn:aws:sns:us-east-1:686681529839:iws-core-supply-proto-001'
          HIVE__BUCKET__NAME: !Sub 'aew-nucleus-food-${AWS::StackName}'
          HIVE__BUCKET__REGION: !Ref 'AWS::Region'
      Policies:
      - 'AWSLambdaBasicExecutionRole'
      - Statement:
        - Sid: 'NuclearFoodPersistencePolicy'
          Effect: Allow
          Action:
            - 's3:PutObject'
            - 's3:GetObject'
            - 's3:GetObjectAttributes'
            - 's3:GetObjectTagging'
            - 's3:DeleteObject'
          Resource: !Sub 'arn:aws:s3:::aew-nucleus-food-${AWS::StackName}/*'
  NucleusFoodS3:
    Type: AWS::S3::Bucket
    Description: 'S3 for AEW Nucleus for Food'
    Properties:
      BucketName: !Sub 'aew-nucleus-food-${AWS::StackName}'
########## END FOOD
Outputs:
  WebEndpoint:
    Description: 'API Gateway endpoint URL'
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/'
  NucleusWaterS3:
    Description: Bucket Created using this template.
    Value: !Ref NucleusWaterS3
  NucleusFoodS3:
    Description: Bucket Created using this template.
    Value: !Ref NucleusFoodS3
