AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template to deploy Nucleus APIs
# Something in this template is causing it to create 2 integrations and is damaging
# the API Proxy to the Lambdas.
# Something has changed since the last time I spun one of these up.
# - According to the logs
# -- The IAM role configured on the integration or API Gateway doesn't have permissions to call the integration. Check the permissions and try again.
# It wasn't doing this a week ago. Either there was a fluke policy lurking somewhere that has since been deleted
# Or CloudFormation changed it's mind on how it spins up the API
# I have confirmed that the API is set to "auto provision", however, it is not doing it.
# We will need to trace down how to create an explicit invoke policy in this template.
Parameters:
  JwtIssuer:
    Type: String
    Description: For AWS Cognito https://cognito-idp.{region}.amazonaws.com/{userPoolId}
  JwtAudience:
    Type: String
    Description: The audience associated with this authorizer
  NucleusSnsArn:
    Type: String
    Description: The ARN of the Nucleus SNS.

Globals:
  Function:
    Timeout: 100

Resources:
  AewGateway:
    Type: "AWS::Serverless::HttpApi"
    Properties:
      StageName: !Sub 'public'
      CorsConfiguration:
        AllowHeaders:
          - "*"
        ExposeHeaders:
          - "*"
        AllowOrigins:
          - "http://localhost:8080"
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
        AllowCredentials: true
      # Auth:
      #   Authorizers:
      #     OAuth2Authorizer:
      #       IdentitySource: "$request.header.Authorization"
      #       JwtConfiguration:
      #         issuer: !Ref JwtIssuer
      #         audience: 
      #         - !Ref JwtAudience
      #   DefaultAuthorizer: OAuth2Authorizer
  NucleusSupplyBusTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "Nucleus Supply Bus"
      FifoTopic: false
      TopicName: !Sub "aew-nucleus-supply-bus-${AWS::StackName}"
  
########### START WATER
  NucleusWaterApi:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Description: API for AEW Nucleus for Water.
      CodeUri: ./AEW.Nucleus.Water.API/src/AEW.Nucleus.Water.API/
      Handler: AEW.Nucleus.Water.API
      Runtime: dotnet6
      MemorySize: 128    
      Events:
        ProxyResource:
          Type: HttpApi
          Properties:
            ApiId: !Ref AewGateway
            PayloadFormatVersion: '2.0'
            Path: water/{proxy+}
            Method: GET
        # RootResource:
        #   PayloadFormatVersion: '2.0'
        #   Type: HttpApi
        #   Properties:
        #     ApiId: !Ref AewGateway
        #     Path: water/
        #     Method: GET
      Environment:
        Variables:
          NUCLEUS_SUPPLY_TOPIC__REGION: !Ref 'AWS::Region'
          NUCLEUS_SUPPLY_TOPIC__ARN: !Ref NucleusSnsArn
          HIVE__BUCKET__NAME: !Sub 'aew-nucleus-water-${AWS::StackName}'
          HIVE__BUCKET__REGION: !Ref 'AWS::Region'
      Policies:
      - 'AWSLambdaBasicExecutionRole'
      - Statement:
        - Sid: 'NuclearWaterPersistencePolicy'
          Effect: Allow
          Action:
            - 's3:PutObject'
            - 's3:GetObject'
            - 's3:GetObjectAttributes'
            - 's3:GetObjectTagging'
            - 's3:DeleteObject'
          Resource: !Sub 'arn:aws:s3:::aew-nucleus-water-${AWS::StackName}/*'
  NucleusWaterS3:
    Type: AWS::S3::Bucket
    Description: 'S3 for AEW Nucleus for Water'
    Properties:
      BucketName: !Sub 'aew-nucleus-water-${AWS::StackName}'
########### END WATER
########### START FOOD
  NucleusFoodApi:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Description: API for AEW Nucleus for Food.
      CodeUri: ./AEW.Nucleus.Food.API/src/AEW.Nucleus.Food.API/
      Handler: AEW.Nucleus.Food.API
      Runtime: dotnet6
      MemorySize: 128    
      Events:
        ProxyResource:
          Type: HttpApi
          Properties:
            ApiId: !Ref AewGateway
            PayloadFormatVersion: '2.0'
            Path: food/{proxy+}
            Method: GET
        # RootResource:
        #   PayloadFormatVersion: '2.0'
        #   Type: HttpApi
        #   Properties:
        #     ApiId: !Ref AewGateway
        #     Path: food/
        #     Method: GET
      Environment:
        Variables:
          NUCLEUS_SUPPLY_TOPIC__REGION: !Ref 'AWS::Region'
          NUCLEUS_SUPPLY_TOPIC__ARN: !Ref NucleusSnsArn
          HIVE__BUCKET__NAME: !Sub 'aew-nucleus-food-${AWS::StackName}'
          HIVE__BUCKET__REGION: !Ref 'AWS::Region'
      Policies:
      - 'AWSLambdaBasicExecutionRole'
      - Statement:
        - Sid: 'NuclearFoodPersistencePolicy'
          Effect: Allow
          Action:
            - 's3:PutObject'
            - 's3:GetObject'
            - 's3:GetObjectAttributes'
            - 's3:GetObjectTagging'
            - 's3:DeleteObject'
          Resource: !Sub 'arn:aws:s3:::aew-nucleus-food-${AWS::StackName}/*'
  NucleusFoodS3:
    Type: AWS::S3::Bucket
    Description: 'S3 for AEW Nucleus for Food'
    Properties:
      BucketName: !Sub 'aew-nucleus-food-${AWS::StackName}'
########## END FOOD
Outputs:
  NucleusWaterS3:
    Description: Bucket Created using this template.
    Value: !Ref NucleusWaterS3
  NucleusFoodS3:
    Description: Bucket Created using this template.
    Value: !Ref NucleusFoodS3
